### ISSUE TITLE
need help or info working with windows

### ISSUE THREAD

**Issue by noobee** [queezythegreat/arduino-cmake#57]
First, thank you for a very nice project!

Second, my apologies if this is not the right forum to discuss this issue. Please redirect me to the right place if appropriate.

I'm having some trouble setting up the environment for a windows machine. i've tried searching for information, discussion forums, or tutorials in this topic, but am unable to find much useful data. Hence, i'm filing this issue. 

I followed the instructions in your tutorial to set up the environment for windows, with the following key parameters,
- installed C:\arduino-1.0.1
- installed C:\Program Files (x86)\CMake 2.8
- installed C:\Users\z570\Desktop\arduino-cmake
- set up the system paths (probably more than really needed):
  C:\arduino-1.0.1;
  C:\arduino-1.0.1\hardware\tools\avr\bin;
  C:\arduino-1.0.1\hardware\tools\avr\avr\bin;
  C:\arduino-1.0.1\hardware\tools\avr\utils\bin;
  C:\Program Files (x86)\CMake 2.8\bin;
- edited C:\Users\z570\Desktop\arduino-cmake\example\CMakeLists.txt to add the following
  cmake_minimum_required(VERSION 2.8)
  set(CMAKE_ARDUINO_PATH "C:/Users/z570/Desktop/arduino-cmake")
  set(CMAKE_MODULE_PATH ${CMAKE_ARDUINO_PATH}/cmake/modules) # CMake module search path
  set(CMAKE_TOOLCHAIN_FILE ${CMAKE_ARDUINO_PATH}/cmake/toolchains/Arduino.cmake) # Arduino Toolchain
- created and cd into C:\Users\z570\Desktop\arduino-cmake\example\build
- run cmake -G"MSYS Makefiles" ..
- and it fails while trying to make the following
  
  Run Build Command:C:/arduino-1.0.1/hardware/tools/avr/utils/bin/make.exe "cmTryCompileExec76835234/fast"

i've attached the full error log (may be for a later run) at 
https://docs.google.com/document/d/1x9LiaN9OlhSii-cPBDriTVF9FhbY37zefvrnbg2HV1Q/pub

i am not sure how to proceed and would love to hear any advice.

thank you!

**Comment by queezythegreat** [comment]
Hi, could you try the following:
1. Put the Arduino SDK into `C:\Program Files\`
2. Add `C:\Program Files\arduino-1.0.1\hardware\tools\avr\utils\bin` onto your system path ( and remove all your previous entries except for CMake)

```
set PATH=%PATH%;C:\Program Files\arduino-1.0.1\hardware\tools\avr\utils\bin
set PATH=%PATH%;C:\Program Files (x86)\CMake 2.8\bin
```
1. Enter the `arduino-cmake` directory, then create a `build` directory and enter it:

```
cd arduino-cmake
mkdir build
cd build
```
1. Confiugre and run:

```
cmake -G"MinGW Makefiles" ..
make
```

By the way, the example provided is expected to work without any modifications, you just need to specify `arduino-cmake` as the source directory.

I tried the following with the latest version of the Arduino SDK version 1.0.3. I did have some problems with the configuration, but that was caused by me having MinGW and MsysGit installed on my system (but fixed the problem by removing the offending entries in the system path).

**Comment by noobee** [comment]
your walkthrough works!!

for some reason, it'll only work if the arduino SDK is located at `c:\program files\arduino-1.0.1` but not when it is located at `c:\arduino-1.0.1`, even after i tried setting the right path and also tried adding `set(ARDUINO_SDK_PATH c:/arduino-1.0.1)` in the top-level `CMakelists.txt`.

i also made the mistake of trying to build from the `./example` subdirectory instead of the top-level `arduino-cmake'.

in any case, i was able to build the example that you provided and i think i should be able to adapt it towards my project. 

one small suggestion i have is to add a note in `README.rst` to try installing the arduino SDK in the preferred `C:\Programs File` path instead of the _SYSTEM PATH_. it made the difference for me.

i would like to thank you very much again for your help!
